{{- with .Values.certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: default-certificate
spec:
    commonName: "{{ .domain }}"
    dnsNames:
      - "{{ .domain }}"
    issuerRef:
        kind: {{ .issuer.kind }}
        name: {{ .issuer.name }}
    secretName: default-certificate
    secretTemplate:
        annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "k2-auth"
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespace: "k2-auth"
{{- end -}}
