{{- with .Values.certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: default-certificate
spec:
    commonName: "{{ .domain }}"
    dnsNames:
      - "{{ .domain }}"
    issuerRef:
        kind: {{ .issuer.kind }}
        name: {{ .issuer.name }}
    secretName: default-certificate
{{- end -}}
