#!/bin/sh -e

PREREQ=""
prereqs() {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# Put PCI device IDs that you wish to bind to VFIO
# Find PCI devices using the 'lspci -D' command
# Example:
#        0000:00:00.0 # Comment
PCI_DEVICES="
{% for device in vfio_devices %}
{{ device }}
{% endfor %}
"

echo "$PCI_DEVICES" | while IFS= read -r LINE; do
	DEVICE=$(echo "$LINE" | cut -d '#' -f 1 | xargs)
	[ -z "$DEVICE" ] && continue
	echo "vfio-pci" > /sys/bus/pci/devices/$DEVICE/driver_override
	echo "bind_vfio: $DEVICE"
done

modprobe -i vfio-pci
