---
- name: create non-admin user
  user:
    name: '{{ user.username }}'
    password: "{{ user.password }}"
    group: wheel
    update_password: always
  register: __user_create

- name: pull SSH key from github
  ansible.posix.authorized_key:
    user: '{{ user.username }}'
    key: 'https://github.com/{{ user.github }}.keys'
    state: present
  register: __user_ssh_keys
