---

- name: Install doas
  apk:
    name: doas
    state: latest
  
- name: Ensure :{{ doas_group }} group exists
  group:
    name: "{{ doas_group }}"
    state: present

- name: Configure :{{ doas_group }} doas permissions
  template:
    src: doas.conf.j2
    dest: /etc/doas.d/doas.conf
    owner: root
    group: root
    mode: 0644
