- name: pull down latest TLS certificates
  block:
    - name: create local certificate directory
      delegate_to: localhost
      run_once: true
      tempfile:
        state: directory
        suffix: ".{{ k2_tls_domain }}"
      changed_when: no
      register: __tls_tempdir

    - name: pull latest TLS certificate for {{ k2_tls_domain }}
      delegate_to: localhost
      run_once: true
      amazon.aws.s3_object:
        bucket: "{{ k2_tls_bucket }}"
        object: "{{ k2_tls_domain}}/{{ item }}"
        dest: "{{ __tls_tempdir.path }}/{{ item }}"
        mode: get
      register: __tls_certs
      changed_when: no
      with_items:
        - fullchain.pem
        - privkey.pem

- import_tasks: pve.yml
  when: "'proxmox' in group_names"
