apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
data:
  Corefile: ".:1053 {\n    k8s_gateway wyvernzora.io {\n      apex k8s-gateway.k2-network\n      ttl 300\n    }\n    log\n    errors\n    health { \n      lameduck 5s\n    }\n    ready\n    prometheus 0.0.0.0:9153\n    forward . /etc/resolv.conf\n    loop\n    reload\n    loadbalance\n}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - "*"
    verbs:
      - watch
      - list
  - apiGroups:
      - k8s.nginx.org
    resources:
      - "*"
    verbs:
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-gateway
subjects:
  - kind: ServiceAccount
    name: k8s-gateway
    namespace: k2-network
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/name: k8s-gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: k8s-gateway-2.4.0
  name: k8s-gateway
  namespace: k2-network
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8s-gateway
      app.kubernetes.io/name: k8s-gateway
  template:
    metadata:
      annotations:
        checksum/config: 4e41ae97e17fa2a1fc02a8387822e83bdb091ac4d1f06b85bab372d67172e9db
      labels:
        app.kubernetes.io/instance: k8s-gateway
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: k8s-gateway
        app.kubernetes.io/version: 0.4.0
        helm.sh/chart: k8s-gateway-2.4.0
    spec:
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          image: quay.io/oriedge/k8s_gateway:v0.4.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          name: k8s-gateway
          ports:
            - containerPort: 1053
              name: dns-udp
              protocol: UDP
            - containerPort: 9153
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
      serviceAccountName: k8s-gateway
      volumes:
        - configMap:
            items:
              - key: Corefile
                path: Corefile
            name: k8s-gateway
          name: config-volume
