/* eslint-disable k2/no-raw-k8s-jobs -- Pomerium bootstrap secrets are generated by running the controller image subcommand directly. */
import { Duration, Size } from "cdk8s";
import {
  Capability,
  Cpu,
  Deployment,
  EnvFieldPaths,
  EnvValue,
  ImagePullPolicy,
  Job,
  LabelSelector,
  Probe,
  Protocol,
  RestartPolicy,
  Volume,
  type ContainerProps,
  type IServiceAccount,
  type Workload,
} from "cdk8s-plus-32";
import type { Construct } from "constructs";

import { linux, only, Scheduling, withReplaceableJobSyncOptions, workers } from "@k2/cdk-lib";

import { POMERIUM_LABELS, POMERIUM_PROXY_SERVICE_NAME } from "../../constants.js";

import { metadata } from "./metadata.js";

const POMERIUM_IMAGE = "pomerium/ingress-controller:v0.32.8";
const TMP_VOLUME_NAME = "tmp";

export function createWorkloads(
  scope: Construct,
  controllerServiceAccount: IServiceAccount,
  genSecretsServiceAccount: IServiceAccount,
): void {
  createControllerDeployment(scope, controllerServiceAccount);
  createGenSecretsJob(scope, genSecretsServiceAccount);
}

function createControllerDeployment(scope: Construct, serviceAccount: IServiceAccount): void {
  const tmpVolume = Volume.fromEmptyDir(scope, "tmp-volume", TMP_VOLUME_NAME);
  const deployMetadata = metadata("pomerium");
  const deployment = new Deployment(scope, "deployment", {
    metadata: {
      ...deployMetadata,
      labels: { ...deployMetadata.labels, ...POMERIUM_LABELS },
    },
    replicas: 1,
    select: false,
    podMetadata: { labels: POMERIUM_LABELS },
    automountServiceAccountToken: true,
    serviceAccount,
    securityContext: { ensureNonRoot: true },
    terminationGracePeriod: Duration.seconds(10),
    containers: [controllerContainer(tmpVolume)],
    volumes: [tmpVolume],
  });

  deployment.select(LabelSelector.of({ labels: POMERIUM_LABELS }));
  applyScheduling(deployment);
}

function createGenSecretsJob(scope: Construct, serviceAccount: IServiceAccount): void {
  const job = new Job(scope, "gen-secrets-job", {
    metadata: withReplaceableJobSyncOptions(metadata("pomerium-gen-secrets")),
    select: false,
    podMetadata: { name: "pomerium-gen-secrets" },
    automountServiceAccountToken: true,
    serviceAccount,
    restartPolicy: RestartPolicy.ON_FAILURE,
    securityContext: {
      fsGroup: 1000,
      ensureNonRoot: true,
      user: 1000,
    },
    containers: [genSecretsContainer()],
  });

  applyScheduling(job);
}

function controllerContainer(tmpVolume: Volume): ContainerProps {
  return {
    name: "pomerium",
    image: POMERIUM_IMAGE,
    imagePullPolicy: ImagePullPolicy.IF_NOT_PRESENT,
    args: controllerArgs(),
    envVariables: controllerEnv(),
    ports: controllerPorts(),
    liveness: httpProbe("/healthz", 28080, 10),
    readiness: httpProbe("/readyz", 28080, 5),
    startup: startupProbe(),
    resources: {
      cpu: {
        request: Cpu.millis(100),
        limit: Cpu.millis(1000),
      },
      memory: {
        request: Size.mebibytes(200),
        limit: Size.gibibytes(1),
      },
    },
    securityContext: {
      allowPrivilegeEscalation: false,
      capabilities: { drop: [Capability.ALL] },
      group: 65532,
      user: 65532,
      ensureNonRoot: true,
      readOnlyRootFilesystem: true,
    },
    volumeMounts: [{ volume: tmpVolume, path: "/tmp" }],
  };
}

function genSecretsContainer(): ContainerProps {
  return {
    name: "gen-secrets",
    image: POMERIUM_IMAGE,
    imagePullPolicy: ImagePullPolicy.IF_NOT_PRESENT,
    args: ["gen-secrets", "--secrets=$(POD_NAMESPACE)/bootstrap"],
    envVariables: {
      POD_NAMESPACE: EnvValue.fromFieldRef(EnvFieldPaths.POD_NAMESPACE),
    },
    resources: {
      cpu: {
        request: Cpu.millis(25),
        limit: Cpu.millis(250),
      },
      memory: {
        request: Size.mebibytes(64),
        limit: Size.mebibytes(256),
      },
    },
    securityContext: { allowPrivilegeEscalation: false },
  };
}

function controllerArgs() {
  return [
    "all-in-one",
    "--pomerium-config=global",
    `--update-status-from-service=$(POMERIUM_NAMESPACE)/${POMERIUM_PROXY_SERVICE_NAME}`,
    "--metrics-bind-address=$(POD_IP):9090",
    "--health-probe-bind-address=$(POD_IP):28080",
  ];
}

function controllerEnv(): Record<string, EnvValue> {
  return {
    TMPDIR: EnvValue.fromValue("/tmp"),
    XDG_CACHE_HOME: EnvValue.fromValue("/tmp"),
    POMERIUM_NAMESPACE: EnvValue.fromFieldRef(EnvFieldPaths.POD_NAMESPACE, { apiVersion: "v1" }),
    POD_IP: EnvValue.fromFieldRef(EnvFieldPaths.POD_IP),
  };
}

function controllerPorts() {
  return [
    { number: 8443, name: "https", protocol: Protocol.TCP },
    { number: 443, name: "quic", protocol: Protocol.UDP },
    { number: 8080, name: "http", protocol: Protocol.TCP },
    { number: 9090, name: "metrics", protocol: Protocol.TCP },
  ];
}

function startupProbe(): Probe {
  return Probe.fromHttpGet("/startupz", {
    port: 28080,
    failureThreshold: 40,
    periodSeconds: Duration.seconds(15),
  });
}

function httpProbe(path: string, port: number, failureThreshold: number): Probe {
  return Probe.fromHttpGet(path, {
    port,
    failureThreshold,
    initialDelaySeconds: Duration.seconds(15),
    periodSeconds: Duration.seconds(60),
  });
}

function applyScheduling(workload: Workload): void {
  Scheduling.of(workload).apply(only(workers()), only(linux()));
}
