apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: k2-core
spec:
  destination:
    namespace: k2-core
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 1password
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 600s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: k2-core
spec:
  destination:
    namespace: k2-core
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 600s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: k2-core
spec:
  destination:
    namespace: k2-auth
    server: https://kubernetes.default.svc
  project: default
  source:
    path: authelia
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 600s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: cert-manager
  namespace: k2-core
spec:
  destination:
    namespace: k2-core
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cert-manager
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: dns
  namespace: k2-core
spec:
  destination:
    namespace: k2-network
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dns
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: glauth
  namespace: k2-core
spec:
  destination:
    namespace: k2-auth
    server: https://kubernetes.default.svc
  project: default
  source:
    path: glauth
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: home-automation
  namespace: k2-core
spec:
  destination:
    namespace: home-automation
    server: https://kubernetes.default.svc
  project: default
  source:
    path: home-automation
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: kube-vip
  namespace: k2-core
spec:
  destination:
    namespace: k2-network
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-vip
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: longhorn
  namespace: k2-core
spec:
  destination:
    namespace: k2-storage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: longhorn
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: media
  namespace: k2-core
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: media
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: metallb
  namespace: k2-core
spec:
  destination:
    namespace: k2-network
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
      kind: CustomResourceDefinition
  project: default
  source:
    path: metallb
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: n8n
  namespace: k2-core
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: default
  source:
    path: n8n
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: plex
  namespace: k2-core
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: plex
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: traefik
  namespace: k2-core
spec:
  destination:
    namespace: k2-network
    server: https://kubernetes.default.svc
  project: default
  source:
    path: traefik
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
