apiVersion: v2
name: cert-manager
version: 1.0.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.19.1
  - name: reflector
    repository: https://emberstack.github.io/helm-charts
    version: 9.1.44
