#cloud-config
hostname: 'k2-{{ "{{ trunc 4 .MachineID }}" }}'

install:
    device: /dev/sda
    poweroff: true

users:
  - name: kairos
    passwd: '{{ op://K2/wyvernzora/passwd }}'
    ssh_authorized_keys:
      - github:wyvernzora

k3s:
    enabled: true
    args:
        # Spin up k3s in cluster mode
      - '--cluster-init'
      - '--token={{op://K2/k2.wyvernzora.io/server-token}}'
      - '--server=10.10.8.2'

        # Make sure k8s control-plane cert has KubeVIP IP
      - '--tls-san=10.10.8.2'

        # We'll be deploying our own Traefik and MetalLB
      - '--disable=traefik,servicelb'

        # Encrypt secrets at rest
      - '--secrets-encryption'

        # Use WireGuard for intra-cluster network
      - '--flannel-backend=wireguard-native'

growpart:
    devices: ['/']
