apiVersion: apps/v1
kind: Deployment
metadata:
  name: anything-llm-depl-c8150999
  namespace: gen-ai
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: anything-llm-depl-c8fd9b7b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: anything-llm-depl-c8fd9b7b
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: STORAGE_DIR
              value: /app/server/storage
          image: mintplexlabs/anythingllm:1.9.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3001
              scheme: HTTP
          name: anything-llm
          ports:
            - containerPort: 3001
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3001
              scheme: HTTP
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/server/storage
              name: pvc-anything-llm-depl-vol-appdata-pvc-c8160e74
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pvc-anything-llm-depl-vol-appdata-pvc-c8160e74
          persistentVolumeClaim:
            claimName: anything-llm-depl-vol-appdata-pvc-c8160e74
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-depl-vol-appdata-pvc-c8160e74
  namespace: gen-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: anything-llm-depl-service-c82f261a
  namespace: gen-ai
spec:
  externalIPs: []
  ports:
    - port: 80
      targetPort: 3001
  selector:
    cdk8s.io/metadata.addr: anything-llm-depl-c8fd9b7b
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth-authelia@kubernetescrd
  name: anything-llm-ingr-c88d824f
  namespace: gen-ai
spec:
  rules:
    - host: ai.wyvernzora.io
      http:
        paths:
          - backend:
              service:
                name: anything-llm-depl-service-c82f261a
                port:
                  number: 80
            path: /
            pathType: Prefix
