---
# Source: authelia/charts/authelia/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.37.5
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.58
data:
  configuration.yaml: |
    ---
    theme: light
    default_redirection_url: https://h.wyvernzora.io
    default_2fa_method: ''
    server:
      host: 0.0.0.0
      port: 9091
      asset_path: ''
      headers:
        csp_template: ''
      buffers:
        read: 4096
        write: 4096
      timeouts:
        read: 6s
        write: 6s
        idle: 30s
      enable_pprof: false
      enable_expvars: false
    log:
      level: info
      format: text
      file_path: ''
      keep_stdout: true
    totp:
      disable: false
      issuer: wyvernzora.io
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    webauthn:
      disable: false
      display_name: Authelia
      attestation_conveyance_preference: indirect
      user_verification: preferred
      timeout: 60s
    ntp:
      address: time.cloudflare.com:123
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      password_reset:
        disable: false
        custom_url: ''
      ldap:
        implementation: custom
        url: ldap://glauth.k2-auth.svc.cluster.local
        timeout: 5s
        start_tls: false
        tls:
          server_name: 'ldap.wyvernzora.io'
          skip_verify: false
          minimum_version: TLS1.2
          maximum_version: TLS1.3
        base_dn: dc=wyvernzora,dc=io
        additional_users_dn: ou=users
        users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=posixAccount))
        additional_groups_dn: ou=groups
        groups_filter: (&(memberUid={username})(objectClass=posixGroup))
        permit_referrals: false
        permit_unauthenticated_bind: false
        permit_feature_detection_failure: false
        user: cn=authelia,dc=wyvernzora,dc=io
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: true
        require_lowercase: true
        require_number: true
        require_special: true
      zxcvbn:
        enabled: false
        min_score: 0
    session:
      name: 'authelia_session'
      domain: 'wyvernzora.io'
      same_site: 'lax'
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
    regulation: 
      ban_time: 5m
      find_time: 2m
      max_retries: 3
    storage:
      local:
        path: /var/authelia/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /var/authelia/notifications.log
    access_control:
      default_policy: one_factor
      networks: 
      - name: private
        networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    ...
---
# Source: authelia/charts/authelia/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.37.5
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.58
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
# Source: authelia/charts/authelia/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.37.5
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.58
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
  revisionHistoryLimit: 5
  replicas: 1
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: authelia
        app.kubernetes.io/instance: authelia
        app.kubernetes.io/version: 4.37.5
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: authelia-0.8.58
      annotations:
        checksum/config: 24b0e554f9bfdc07d893ae12103ed5d37faa34ebb05dfb771da70bd48bd4bd6e
        
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity: 
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      enableServiceLinks: false
      containers:
      - name: authelia
        image: ghcr.io/authelia/authelia:4.37.5
        imagePullPolicy: IfNotPresent
        command: ["authelia"]
        args:
        - --config=/configuration.yaml
        resources: 
          limits: {}
          requests: {}
        env:
        - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
          value: "true"
        - name: AUTHELIA_JWT_SECRET_FILE
          value: /secrets/JWT_TOKEN
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: /secrets/SESSION_ENCRYPTION_KEY
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
          value: /secrets/LDAP_PASSWORD
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: /secrets/STORAGE_ENCRYPTION_KEY
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - mountPath: /configuration.yaml
          name: config
          readOnly: true
          subPath: configuration.yaml
        - mountPath: /secrets
          name: secrets
          readOnly: true
        - mountPath: /var/authelia/
          name: ephemeral
      volumes:
      - name: config
        configMap:
          name: authelia
          items:
          - key: configuration.yaml
            path: configuration.yaml
      - name: secrets
        secret:
          secretName: authelia
          items:
          - key: JWT_TOKEN
            path: JWT_TOKEN
          - key: SESSION_ENCRYPTION_KEY
            path: SESSION_ENCRYPTION_KEY
          - key: STORAGE_ENCRYPTION_KEY
            path: STORAGE_ENCRYPTION_KEY
          - key: LDAP_PASSWORD
            path: LDAP_PASSWORD
      - emptyDir: {}
        name: ephemeral
---
# Source: authelia/charts/authelia/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.37.5
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.58
spec:
  rules:
    - host: auth.wyvernzora.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 80
---
# Source: authelia/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
spec:
  forwardAuth:
    address: http://authelia.k2-auth.svc.cluster.local/api/verify?rd=https%3A%2F%2Fauth.wyvernzora.io%2F
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Email"
      - "Remote-Name"
---
# Source: authelia/templates/secret.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
    name: authelia
    namespace: "k2-auth"
spec:
    itemPath: "vaults/zfsyjjcwge4w4gw6dh4zaqndhq/items/ejfcz3g4s6wsr2jtct6hs3alxi"
