---

- name: Install docker packages
  apk:
    name: '{{ item }}'
    state: latest
  with_items:
   - docker
   - docker-compose

- name: Enable docker service
  service:
    name: docker
    enabled: yes
    runlevel: boot
    state: started

- name: Create docker directory
  file:
    path: /docker
    state: directory

- name: Create directories for docker-compose stacks
  file:
    path: /docker/{{ item }}
    state: directory
  with_items:
    - portainer

- name: Copy over docker-compose files
  copy:
    src: '{{ item }}.yaml'
    dest: '/docker/{{ item }}/docker-compose.yaml'
  with_items:
    - portainer

- name: Start up docker-compose stacks
  shell:
    cmd: docker-compose up -d
    chdir: /docker/{{ item }}
  with_items:
    - portainer
