---
- name: install fish shell
  block:
      - name: add fish apt repository
        apt_repository:
            repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_{{ ansible_distribution_major_version }}/ /"
            state: present
            update_cache: false
        register: __fish_repo

      - name: download and trust fish repository signing key
        shell:
            cmd: |
                curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_{{ ansible_distribution_major_version }}/Release.key |\
                gpg --dearmor -o /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg
        when: __fish_repo.changed

      - name: update cache
        ansible.builtin.apt:
            update_cache: yes
        when: __fish_repo.changed

      - name: install fish
        apt:
            name: fish
            state: latest
        register: __install_fish

- name: configure fish shell
  block:
      - name: ensure config directory exists
        ansible.builtin.file:
            path: ~{{ item }}/.config/fish/functions
            owner: "{{ item }}"
            state: directory
        loop:
          - "root"
          - "{{ user.username }}"

      - name: install fisher
        ansible.builtin.get_url:
            url: https://git.io/fisher
            dest: ~{{ item }}/.config/fish/functions/fisher.fish
        loop:
          - "root"
          - "{{ user.username }}"


      - name: copy fisher plugins file
        copy:
            src: files/fish_plugins
            dest: ~{{ item }}/.config/fish/fish_plugins
        diff: true
        register: __fisher_config
        loop:
          - "root"
          - "{{ user.username }}"


      - name: update fisher plugins
        ansible.builtin.shell:
            cmd: "fisher update"
            executable: /bin/fish
        when: __fisher_config.changed
        register: __fisher_update
        loop:
          - "root"
          - "{{ user.username }}"

      - name: copy fish config file
        ansible.builtin.copy:
            src: files/config.fish
            dest: ~{{ item }}/.config/fish/config.fish
            owner: "{{ item }}"
            mode: 0755
        loop:
          - "root"
          - "{{ user.username }}"

      - name: make fish default shell
        user:
            name: "{{ item }}"
            shell: /usr/bin/fish
        loop:
          - "root"
          - "{{ user.username }}"

      - name: make sure ownership is correct
        file:
          path: "~{{ item }}/.config"
          owner: "{{ item }}"
          group: "{{ item }}"
          recurse: yes
          state: directory
        loop:
          - "root"
          - "{{ user.username }}"
