---
- name: set up sudo and wheel group
  block:
      - name: install sudo
        package:
            name: sudo
            state: present

      - name: create wheel group
        group:
            name: wheel
            state: present
    
      - name: allow wheel group to sudo with no password
        community.general.sudoers:
            name: wheel
            commands: ALL
            group: wheel
