---
- name: create non-admin user group
  group:
      gid: "{{ user.gid }}"
      name: "{{ user.username }}"


- name: create non-admin user
  user:
      uid: "{{ user.uid }}"
      name: "{{ user.username }}"
      password: "{{ user.password }}"
      group: "{{ user.username }}"
      groups:
        - wheel
      update_password: always
  register: __user_create

- name: set up authorized SSH keys
  authorized_key:
      user: "{{ user.username }}"
      key: "{{ item }}"
      state: present
  with_items: "{{ user.sshkeys }}"
  register: __user_ssh_keys

- name: add user to PVE
  pveum_user:
      username: wyvernzora

- name: grant user PVE admin permissions
  pveum_acl:
      username: wyvernzora
      role: Administrator
      path: /
