#
# Default address pool that can only be accessed from
# non-sandboxed VLANs.
#
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: default-pool
    namespace: {{ $.Release.Namespace }}
spec:
    addresses:
      - 10.10.12.1-10.10.12.254
