---
- name: validate nginx configuration
  command: nginx -t
  changed_when: false
  listen: restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
  listen: restart nginx
