{{/* renovate: depName=argo-cd repoUrl=https://argoproj.github.io/argo-helm */}}
{{- $version := "5.51.0" -}}

{{- with default({} .Config.argocd) -}}
apiVersion: v1
kind: Namespace
metadata:
    name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: argocd
    namespace: argocd
spec:
    chart: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: "{{ default $version .version }}"
    valuesContent: |-
        secret:
            createSecret: false
        configs:
            params:
                # TLS termination by Traefik
                server.insecure: true
            cm:
                statusbadge.enabled: 'true'
                resource.customizations.health.argoproj.io_Application: |
                    hs = {}
                    hs.status = "Progressing"
                    hs.message = ""
                    if obj.status ~= nil then
                    if obj.status.health ~= nil then
                        hs.status = obj.status.health.status
                        if obj.status.health.message ~= nil then
                        hs.message = obj.status.health.message
                        end
                    end
                    end
                    return hs
            global:
                tolerations:
                  - key: "CriticalAddonsOnly"
                    operator: "Exists"
{{- end -}}
