---
apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: k2-core
type: Opaque
stringData:
    1password-credentials.json: "{{ .Config.onepassword.credentials }}"
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: k2-core
type: Opaque
stringData:
    token: "{{ .Config.onepassword.token }}"
