kube-vip:
  config:
    address: 10.10.8.2
  env:
    cp_enable: "true"
    svc_enable: "false"
    vip_leaderelection: "true"
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
