apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v3-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v3/apps/argocd
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v3-cilium
  namespace: argocd
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v3/apps/cilium
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v3-kube-vip
  namespace: argocd
spec:
  destination:
    namespace: kube-vip
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v3/apps/kube-vip
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
