apiVersion: cnpg.wyvernzora.io/v1alpha1
kind: DatabaseClaim
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai
  namespace: takuhai
spec:
  clusterRef:
    name: nexus
    namespace: postgresql
  databaseName: takuhai
  deletionPolicy: Retain
  schemas:
    - public
---
apiVersion: cnpg.wyvernzora.io/v1alpha1
kind: RoleClaim
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai
  namespace: takuhai
spec:
  access: Owner
  databaseClaimRef:
    name: takuhai
  roleName: takuhai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai
  namespace: takuhai
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/name: takuhai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: takuhai
        cdk8s.io/metadata.addr: takuhai-deployment-c89ef65d
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TAKUHAI_TRANSPORT
              value: http
            - name: TAKUHAI_ADDR
              value: :8080
            - name: TAKUHAI_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: takuhai-credentials
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/wyvernzora/takuhai:dev
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
          name: takuhai
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 1Gi
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: crawler-dmhy
  namespace: takuhai
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: crawler-dmhy
      app.kubernetes.io/name: takuhai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: crawler-dmhy
        app.kubernetes.io/name: takuhai
        cdk8s.io/metadata.addr: takuhai-crawler-deployment-c87e4644
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TAKUHAI_DMHY_ADDR
              value: :8080
            - name: TAKUHAI_DMHY_BASE_URL
              value: https://share.dmhy.org
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/wyvernzora/takuhai/crawler-dmhy:dev
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 6
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          name: crawler-dmhy
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            periodSeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai
  namespace: takuhai
spec:
  externalIPs: []
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: takuhai
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai-mcp
  namespace: takuhai
spec:
  externalIPs: []
  ports:
    - name: mcp
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: takuhai
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: takuhai-crawler-dmhy
  namespace: takuhai
spec:
  externalIPs: []
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/component: crawler-dmhy
    app.kubernetes.io/name: takuhai
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/mcp_server: "true"
    ingress.pomerium.io/mcp_server_path: /mcp
    ingress.pomerium.io/policy: |
      - allow:
          and:
            - authenticated_user: true
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: takuhai
  name: mcp-ingress
  namespace: takuhai
spec:
  ingressClassName: pomerium
  rules:
    - host: takuhai.wyvernzora.io
      http:
        paths:
          - backend:
              service:
                name: takuhai-mcp
                port:
                  name: mcp
            path: /mcp
            pathType: Prefix
  tls:
    - hosts:
        - takuhai.wyvernzora.io
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: namespace-boundary
  namespace: takuhai
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: takuhai
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: takuhai
    - fromEntities:
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: pomerium-takuhai-pomerium-to-takuhai-mcp
specs:
  - description: pomerium to takuhai
    egress:
      - toEndpoints:
          - matchLabels:
              app.kubernetes.io/component: service
              app.kubernetes.io/name: takuhai
              k8s:io.kubernetes.pod.namespace: takuhai
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: proxy
        app.kubernetes.io/name: pomerium
        k8s:io.kubernetes.pod.namespace: pomerium
  - description: pomerium to takuhai
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: takuhai
        k8s:io.kubernetes.pod.namespace: takuhai
    ingress:
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/component: proxy
              app.kubernetes.io/name: pomerium
              k8s:io.kubernetes.pod.namespace: pomerium
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: takuhai-crawler-dmhy-egress
specs:
  - egress:
      - toFQDNs:
          - matchName: dmhy.org
          - matchName: share.dmhy.org
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: crawler-dmhy
        app.kubernetes.io/name: takuhai
        k8s:io.kubernetes.pod.namespace: takuhai
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: takuhai-postgresql-takuhai-to-postgresql
specs:
  - description: takuhai to nexus-postgresql
    egress:
      - toEndpoints:
          - matchLabels:
              cnpg.io/cluster: nexus
              k8s:io.kubernetes.pod.namespace: postgresql
        toPorts:
          - ports:
              - port: "5432"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: takuhai
        k8s:io.kubernetes.pod.namespace: takuhai
  - description: takuhai to nexus-postgresql
    endpointSelector:
      matchLabels:
        cnpg.io/cluster: nexus
        k8s:io.kubernetes.pod.namespace: postgresql
    ingress:
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/component: service
              app.kubernetes.io/name: takuhai
              k8s:io.kubernetes.pod.namespace: takuhai
        toPorts:
          - ports:
              - port: "5432"
                protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: takuhai-metrics
  namespace: takuhai
spec:
  namespaceSelector:
    matchNames:
      - takuhai
  podMetricsEndpoints:
    - portNumber: 8080
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/name: takuhai
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: takuhai-takuhai-metrics-ingress
specs:
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: takuhai
        k8s:io.kubernetes.pod.namespace: takuhai
    ingress:
      - fromEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: takuhai
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: prometheus
              k8s:io.kubernetes.pod.namespace: prometheus
              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: crawler-dmhy-metrics
  namespace: takuhai
spec:
  namespaceSelector:
    matchNames:
      - takuhai
  podMetricsEndpoints:
    - portNumber: 8080
  selector:
    matchLabels:
      app.kubernetes.io/component: crawler-dmhy
      app.kubernetes.io/name: takuhai
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: takuhai
    k2.wyvernzora.io/component: network-policy
  name: takuhai-crawler-dmhy-metrics-ingress
specs:
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/component: crawler-dmhy
        app.kubernetes.io/name: takuhai
        k8s:io.kubernetes.pod.namespace: takuhai
    ingress:
      - fromEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: takuhai
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: prometheus
              k8s:io.kubernetes.pod.namespace: prometheus
              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
