---
- name: remove proxmox enterprise repo
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve {{ansible_distribution_release}} pve-enterprise
    state: absent
    update_cache: no
  become: yes

- name: add proxmox no-subscription repo
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ansible_distribution_release}} pve-no-subscription
    state: present
    update_cache: no
  become: yes
  register: repos

- name: update cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  when: repos.changed

- name: check if subscription warning is already disabled
  shell:
    cmd: |
      grep -n -B 1 'No valid sub' proxmoxlib.js | grep 'void({'
    chdir: /usr/share/javascript/proxmox-widget-toolkit
  changed_when: no
  become: yes
  register: __pve_sub_warning_check

- name: debug
  debug:
    msg: '{{__pve_sub_warning_check}}'

- name: remove no subscription warning
  shell:
    cmd: |
      sed -Ezi.bkp "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" proxmoxlib.js
      systemctl restart pveproxy.service
    chdir: '/usr/share/javascript/proxmox-widget-toolkit'
  become: yes
  when: __pve_sub_warning_check.stdout == ""
