apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
  namespace: blocky
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
  namespace: blocky
data:
  Corefile: |-
    .:1053 {
        k8s_gateway wyvernzora.io {
          apex k8s-gateway.blocky
          ttl 60
          resources Ingress Service HTTPRoute
          fallthrough
        }
        log
        errors
        hosts { 
          ttl 60
          10.10.1.1 unifi.wyvernzora.io
          10.10.7.1 roxy.wyvernzora.io
          10.10.7.2 eris.wyvernzora.io
          10.10.7.3 sylphy.wyvernzora.io
          10.10.7.254 pve.wyvernzora.io
          10.10.8.1 rumi.wyvernzora.io
          10.10.13.1 login.wyvernzora.io
          10.10.9.1 k8s.wyvernzora.io
          fallthrough
        }
        health { 
          lameduck 5s
        }
        ready
        prometheus 0.0.0.0:9153
        forward . 1.1.1.1 9.9.9.9
        cache 30
        loop
        reload
        loadbalance
      }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - "*"
    verbs:
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-gateway
subjects:
  - kind: ServiceAccount
    name: k8s-gateway
    namespace: blocky
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
  namespace: blocky
spec:
  clusterIP: 10.43.250.122
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  selector:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/name: k8s-gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: k8s-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: k8s-gateway-3.7.1
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: k8s-gateway
  name: k8s-gateway
  namespace: blocky
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8s-gateway
      app.kubernetes.io/name: k8s-gateway
  template:
    metadata:
      annotations:
        checksum/config: 830884679b886599ff58ebb6e2707e82ae3384b938f58acbdae384e6de373fce
      labels:
        app.kubernetes.io/instance: k8s-gateway
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: k8s-gateway
        app.kubernetes.io/version: 1.8.0
        helm.sh/chart: k8s-gateway-3.7.1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 100
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          image: ghcr.io/k8s-gateway/k8s_gateway:1.7.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          name: k8s-gateway
          ports:
            - containerPort: 1053
              name: dns-udp
              protocol: UDP
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
            - containerPort: 9153
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
      priorityClassName: system-cluster-critical
      securityContext: {}
      serviceAccountName: k8s-gateway
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - configMap:
            items:
              - key: Corefile
                path: Corefile
            name: k8s-gateway
          name: config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: coredns-forward
  name: coredns-custom
  namespace: kube-system
data:
  apex.server: |
    wyvernzora.io:53 {
        errors
        forward . 10.43.250.122
        cache 30
        reload
    }
immutable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: blocky
  name: blocky-config
  namespace: blocky
data:
  blocky.yaml: |
    log:
      level: info
    upstreams:
      groups:
        10.42.0.0/16:
          - tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
        10.43.0.0/16:
          - tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
        10.1.0.0/16:
          - tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
        10.2.0.0/16:
          - 1.1.1.1
          - 9.9.9.9
        10.8.0.0/16:
          - tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
        10.10.0.0/16:
          - tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
        default:
          - 1.1.1.1
          - 9.9.9.9
    conditional:
      fallbackUpstream: false
      mapping:
        wyvernzora.io: tcp+udp:k8s-gateway.blocky.svc.cluster.local:53
    blocking:
      whiteLists:
        default: []
      blackLists:
        default:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        10.42.0.0/16:
          - default
        10.43.0.0/16:
          - default
        10.1.0.0/16:
          - default
        10.2.0.0/16:
          - default
        10.8.0.0/16:
          - default
        10.10.0.0/16:
          - default
        default:
          - default
    ports:
      dns: 53
      http: 4000
    prometheus:
      enable: true
      path: /metrics
immutable: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: blocky
  name: blocky
  namespace: blocky
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: resolver
      app.kubernetes.io/name: blocky
  template:
    metadata:
      annotations:
        checksum/blocky-config: 770981a1b81b7ff023bde4710d0cb6bdc69780c750551f9be9e37231fbc66d88
      labels:
        app.kubernetes.io/component: resolver
        app.kubernetes.io/name: blocky
        cdk8s.io/metadata.addr: blocky-daemon-set-c8d4d8a1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 100
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/0xerr0r/blocky:v0.26.2
          imagePullPolicy: IfNotPresent
          name: blocky
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 4000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/config.yml
              name: config
              subPath: blocky.yaml
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - configMap:
            name: blocky-config
          name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 10.10.10.10
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: blocky
  name: blocky
  namespace: blocky
spec:
  externalIPs: []
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    app.kubernetes.io/component: resolver
    app.kubernetes.io/name: blocky
  type: LoadBalancer
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: namespace-boundary
  namespace: blocky
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: blocky
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: blocky
    - fromEntities:
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: blocky-blocky-dns
specs:
  - egress:
      - toCIDR:
          - 1.1.1.1/32
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - toCIDR:
          - 9.9.9.9/32
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - toEndpoints:
          - matchLabels:
              k8s-app: kube-dns
              k8s:io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
      - toFQDNs:
          - matchName: raw.githubusercontent.com
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: resolver
        app.kubernetes.io/name: blocky
        k8s:io.kubernetes.pod.namespace: blocky
    ingress:
      - fromCIDR:
          - 10.0.0.0/8
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - fromCIDR:
          - 172.16.0.0/12
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - fromCIDR:
          - 192.168.0.0/16
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - fromCIDR:
          - 100.64.0.0/10
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - fromEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: tailscale
              tailscale.com/managed: "true"
              tailscale.com/parent-resource: k2-router
              tailscale.com/parent-resource-type: connector
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: blocky-k8s-gateway-dns
specs:
  - egress:
      - toCIDR:
          - 1.1.1.1/32
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
      - toCIDR:
          - 9.9.9.9/32
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/instance: k8s-gateway
        app.kubernetes.io/name: k8s-gateway
        k8s:io.kubernetes.pod.namespace: blocky
    ingress:
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
      - fromEntities:
          - remote-node
        toPorts:
          - ports:
              - port: "8080"
                protocol: TCP
      - fromEntities:
          - cluster
        toPorts:
          - ports:
              - port: "1053"
                protocol: UDP
              - port: "1053"
                protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: blocky-metrics
  namespace: blocky
spec:
  namespaceSelector:
    matchNames:
      - blocky
  podMetricsEndpoints:
    - portNumber: 4000
  selector:
    matchLabels:
      app.kubernetes.io/component: resolver
      app.kubernetes.io/name: blocky
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: prometheus-blocky-blocky-metrics-network
specs:
  - description: prometheus to blocky
    egress:
      - toEndpoints:
          - matchLabels:
              app.kubernetes.io/component: resolver
              app.kubernetes.io/name: blocky
              k8s:io.kubernetes.pod.namespace: blocky
        toPorts:
          - ports:
              - port: "4000"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/name: prometheus
        k8s:io.kubernetes.pod.namespace: prometheus
        operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  - description: prometheus to blocky
    endpointSelector:
      matchLabels:
        app.kubernetes.io/component: resolver
        app.kubernetes.io/name: blocky
        k8s:io.kubernetes.pod.namespace: blocky
    ingress:
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: prometheus
              k8s:io.kubernetes.pod.namespace: prometheus
              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
        toPorts:
          - ports:
              - port: "4000"
                protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: k8s-gateway-metrics
  namespace: blocky
spec:
  namespaceSelector:
    matchNames:
      - blocky
  podMetricsEndpoints:
    - portNumber: 9153
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8s-gateway
      app.kubernetes.io/name: k8s-gateway
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    k2.wyvernzora.io/app: blocky
    k2.wyvernzora.io/component: network-policy
  name: prometheus-blocky-k8s-gateway-metrics-network
specs:
  - description: prometheus to k8s-gateway
    egress:
      - toEndpoints:
          - matchLabels:
              app.kubernetes.io/instance: k8s-gateway
              app.kubernetes.io/name: k8s-gateway
              k8s:io.kubernetes.pod.namespace: blocky
        toPorts:
          - ports:
              - port: "9153"
                protocol: TCP
    endpointSelector:
      matchLabels:
        app.kubernetes.io/name: prometheus
        k8s:io.kubernetes.pod.namespace: prometheus
        operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  - description: prometheus to k8s-gateway
    endpointSelector:
      matchLabels:
        app.kubernetes.io/instance: k8s-gateway
        app.kubernetes.io/name: k8s-gateway
        k8s:io.kubernetes.pod.namespace: blocky
    ingress:
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: prometheus
              k8s:io.kubernetes.pod.namespace: prometheus
              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
        toPorts:
          - ports:
              - port: "9153"
                protocol: TCP
