apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config-c8f86e85
data:
  blocky.yaml: |
    log:
      level: debug
    upstream:
      default:
        - 1.1.1.1
    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true
      mapping:
        unifi.wyvernzora.io: 10.10.1.1
        roxy.wyvernzora.io: 10.10.7.1
        eris.wyvernzora.io: 10.10.7.2
        sylphy.wyvernzora.io: 10.10.7.3
        pve.wyvernzora.io: 10.10.7.254
        rumi.wyvernzora.io: 10.10.8.1
        k8s.wyvernzora.io: 10.10.8.2
    conditional:
      fallbackUpstream: true
      mapping:
        wyvernzora.io: k8s-gateway.k2-network.svc.cluster.local
    blocking:
      blackLists:
        default:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - default
    ports:
      dns: 53
      http: 4000
immutable: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: 667f4f3b8d8f4e95a8a741c743a516ed808cc67f8987ca6dbdd188f5ea7b2df3
  name: blocky-depl-c878fc6f
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: blocky-depl-c8cb24d0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: blocky-depl-c8cb24d0
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/0xerr0r/blocky
          imagePullPolicy: Always
          name: blocky
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 4000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/config.yml
              name: configmap-blocky-config-c8f86e85
              subPath: blocky.yaml
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: blocky-config-c8f86e85
          name: configmap-blocky-config-c8f86e85
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.10.8
  name: blocky
spec:
  externalIPs: []
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    cdk8s.io/metadata.addr: blocky-depl-c8cb24d0
  type: LoadBalancer
