#
# Sandbox address pool that is accessible from sandboxed VLANs.
# Due to security considerations IPs from this pool are never assigned
# unless explicitly specified in LoadBalancer spec.
#
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: sandbox-pool
    namespace: {{ $.Release.Namespace }}
spec:
    autoAssign: false
    addresses:
      - 10.10.10.0-10.10.10.254
