- name: Import k2.user
  import_role:
    name: k2.user

- name: add user to PVE
  pveum_user:
      username: "{{ user.username }}"

- name: grant user PVE admin permissions
  pveum_acl:
      username: "{{ user.username }}"
      role: Administrator
      path: /
