# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine315"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 2
    v.linked_clone = true
  end

  config.vm.provider :parallels do |v|
    v.memory = 4096
    v.cpus = 2
    v.linked_clone = true
  end

  # Control Node 1
  config.vm.define "control1" do |control1|
    control1.vm.hostname = "control1"
    control1.vm.network "private_network", ip: "192.168.30.38"
  end

  # Control Node 2
  config.vm.define "control2" do |control2|
      control2.vm.hostname = "control2"
      control2.vm.network "private_network", ip: "192.168.30.39"
  end

  # Control Node 3
  config.vm.define "control3" do |control3|
      control3.vm.hostname = "control3"
      control3.vm.network "private_network", ip: "192.168.30.40"
  end

  # Worker Node 1
  config.vm.define "worker1" do |worker1|
      worker1.vm.hostname = "worker1"
      worker1.vm.network "private_network", ip: "192.168.30.41"
  end

  # Worker Node 2
  config.vm.define "worker2" do |worker2|
      worker2.vm.hostname = "worker2"
      worker2.vm.network "private_network", ip: "192.168.30.42"
  end

  config.vm.provision "shell", inline: "apk add python3"

  config.vm.provision "ansible",type: "ansible", run: "never" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "../main.yml"
    ansible.groups = {
      "master" => ["control1", "control2", "control3"],
      "worker" => ["worker1", "worker2"],
      "all:children" => ["master", "worker"],
    }
    ansible.extra_vars = {
      kube_vip_address: "10.10.1.4",
      interpreter_python: "silent_auto",
    }
  end

end
