---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: k2-root
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: '0'
spec:
    destination:
        namespace: argocd
        server: https://kubernetes.default.svc
    project: default
    source:
        path: gitops
        repoURL: https://github.com/wyvernzora/k2
        targetRevision: main
        helm:
            skipCrds: true
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        retry:
            limit: 10
            backoff:
                duration: 1m
                maxDuration: 16m
                factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
