#cloud-config
hostname: 'k2-{{ "{{ trunc 4 .MachineID }}" }}'

install:
    device: /dev/sda
    poweroff: true

users:
  - name: kairos
    passwd: '{{ op://zfsyjjcwge4w4gw6dh4zaqndhq/ktkj6e2nqloze24qu5yc7eddiy/passwd }}'
    ssh_authorized_keys:
      - github:wyvernzora

growpart:
    devices: ['/']

k3s:
    enabled: true
    env:
      K3S_TOKEN: "{{ op://zfsyjjcwge4w4gw6dh4zaqndhq/xnuknpx3mjqgrgqd7ybv3u7wpy/node-token }}"
    args:
        # Spin up k3s in cluster mode
      - '--cluster-init'
      - '--server=10.10.8.2'

        # Make sure k8s control-plane cert has KubeVIP IP
      - '--tls-san=10.10.8.2'

        # We'll be deploying our own Traefik and MetalLB
      - '--disable=traefik,servicelb'

        # Encrypt secrets at rest
      - '--secrets-encryption'

        # Use WireGuard for intra-cluster network
      - '--flannel-backend=wireguard-native'
