#cloud-config
hostname: 'k2-{{ "{{ trunc 4 .MachineID }}" }}'

users:
  - name: kairos
    passwd: '{{ op://K2/wyvernzora/passwd }}'
    ssh_authorized_keys:
      - github:wyvernzora

growpart:
    devices: ['/']

k3s-agent:
    enabled: true
    env:
      K3S_TOKEN: "{{ op://K2/k2.wyvernzora.io/node-token }}"
      K3S_URL: "https://10.10.8.2:6443"
