{{/* renovate: depName=connect repoUrl=https://1password.github.io/connect-helm-charts */}}
{{- $version := "1.14.0" -}}

{{- with .Config.onepassword -}}
apiVersion: v1
kind: Namespace
metadata:
    name: 1password
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: 1password-connect
    namespace: 1password
spec:
    chart: connect
    repo: https://1password.github.io/connect-helm-charts
    version: "{{ default $version .version }}"
    valuesContent: |-
        connect:
            credentials_base64: "{{ .credentials }}"
        operator:
            create: true
            token:
                value: "{{ .token }}"
{{- end -}}
