apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: csi-nfs-controller-sa
  namespace: nfs-csi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: csi-nfs-node-sa
  namespace: nfs-csi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs-csi
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
parameters:
  onDelete: retain
  server: 10.10.8.1
  share: /mnt/data/volumes/nfs-csi
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs-external-provisioner-role
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs-external-resizer-role
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs-csi-resizer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-external-resizer-role
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: nfs-csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs-csi-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-external-provisioner-role
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: nfs-csi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: csi-nfs-node
  namespace: nfs-csi
spec:
  selector:
    matchLabels:
      app: csi-nfs-node
  template:
    metadata:
      labels:
        app: csi-nfs-node
        app.kubernetes.io/instance: csi-driver-nfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: csi-driver-nfs
        app.kubernetes.io/version: 4.13.3
        helm.sh/chart: csi-driver-nfs-4.13.3
    spec:
      containers:
        - args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29653
            - --v=2
          image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0
          imagePullPolicy: IfNotPresent
          name: liveness-probe
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --v=2
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --timeout=60s
            - --http-endpoint=localhost:19809
          env:
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi-nfsplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              host: localhost
              path: /healthz
              port: healthz
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
          name: node-driver-registrar
          ports:
            - containerPort: 19809
              name: healthz
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --drivername=nfs.csi.k8s.io
            - --mount-permissions=0
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          image: registry.k8s.io/sig-storage/nfsplugin:v4.13.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29653
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: nfs
          resources:
            limits:
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pods-mount-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: csi-nfs-node-sa
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-nfsplugin
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: pods-mount-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: 4.13.3
    helm.sh/chart: csi-driver-nfs-4.13.3
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: csi-nfs-controller
  namespace: nfs-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-nfs-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csi-nfs-controller
        app.kubernetes.io/instance: csi-driver-nfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: csi-driver-nfs
        app.kubernetes.io/version: 4.13.3
        helm.sh/chart: csi-driver-nfs-4.13.3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - -v=2
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=nfs-csi
            - --extra-create-metadata=true
            - --feature-gates=HonorPVReclaimPolicy=true,VolumeAttributesClass=false
            - --timeout=1200s
            - --retry-interval-max=30m
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
          imagePullPolicy: IfNotPresent
          name: csi-provisioner
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - -csi-address=$(ADDRESS)
            - -v=2
            - -leader-election
            - --leader-election-namespace=nfs-csi
            - -handle-volume-inuse-error=false
            - -feature-gates=VolumeAttributesClass=false
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-resizer:v2.0.0
          imagePullPolicy: IfNotPresent
          name: csi-resizer
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29652
            - --v=2
          image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0
          imagePullPolicy: IfNotPresent
          name: liveness-probe
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --drivername=nfs.csi.k8s.io
            - --mount-permissions=0
            - --working-mount-dir=/tmp
            - --default-ondelete-policy=delete
            - --use-tar-command-in-snapshot=false
            - --enable-snapshot-compression=true
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          image: registry.k8s.io/sig-storage/nfsplugin:v4.13.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29652
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: nfs
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pods-mount-dir
            - mountPath: /csi
              name: socket-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: csi-nfs-controller-sa
      volumes:
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: pods-mount-dir
        - emptyDir: {}
          name: socket-dir
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: nfs.csi.k8s.io
spec:
  attachRequired: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: csi-nfs-controller-sa-leader-election
  namespace: nfs-csi
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k2.wyvernzora.io/app: nfs-csi
    k2.wyvernzora.io/component: nfs-csi
  name: rolebindingc87be6934398964b3bc4b85d72ec9b8c49-c82c338e
  namespace: nfs-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-nfs-controller-sa-leader-election
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: nfs-csi
