VERSION 0.8
FROM ghcr.io/wyvernzora/k2-build:latest
COPY . /app
WORKDIR /app

crd-manifest:
    # TODO

crd-constructs:
    RUN /scripts/generate-crd-constructs.sh /app
    SAVE ARTIFACT crds/*.ts AS LOCAL crds/

images:
    RUN echo "{}" > /app/images.json
    SAVE ARTIFACT images.json AS LOCAL dist/images.json
    # This application does not produce container images
