apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Core
  - https://github.com/1Password/onepassword-operator/config/crd?ref=v1.8.1
  - https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.10.5
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml

    # Network
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml
  - https://github.com/metallb/metallb/config/crd?ref=v0.14.4
  - https://github.com/traefik/traefik-helm-chart/traefik/crds?ref=v27.0.0
