apiVersion: v1
kind: ConfigMap
metadata:
  name: glauth-config-c8503900
data:
  config.cfg: "\n[ldap]\n    enabled = true\n    listen = \"0.0.0.0:389\"\n[ldaps]\n    enabled = false\n[backend]\n    datastore = \"config\"\n    baseDN = \"dc=wyvernzora,dc=io\"\n[behaviors]\n    IgnoreCapabilities = false\n    LimitFailedBinds = true\n    NumberOfFailedBinds = 3\n    PeriodOfFailedBinds = 10\n    BlockFailedBindsFor = 60\n    PruneSourceTableEvery = 600\n    PruneSourcesOlderThan = 600\n        "
immutable: false
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: glauth-users-c84bf422
spec:
  itemPath: vaults/zfsyjjcwge4w4gw6dh4zaqndhq/items/7p4cogd3voxt6sonqlj6jb3q4a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glauth-depl-c88d72f7
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: glauth-depl-c8a7ff94
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: glauth-depl-c8a7ff94
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /app/glauth
            - -c
            - /app/conf.d/
          image: glauth/glauth:v2.4.0
          imagePullPolicy: Always
          name: glauth
          ports:
            - containerPort: 389
              name: ldap
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/conf.d/config.cfg
              name: configmap-glauth-config-c8503900
              subPath: config.cfg
            - mountPath: /app/conf.d/users.cfg
              name: secret-glauth-users-c84bf422
              subPath: users.conf
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: glauth-config-c8503900
          name: configmap-glauth-config-c8503900
        - name: secret-glauth-users-c84bf422
          secret:
            secretName: glauth-users-c84bf422
---
apiVersion: v1
kind: Service
metadata:
  name: glauth
spec:
  externalIPs: []
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 389
  selector:
    cdk8s.io/metadata.addr: glauth-depl-c8a7ff94
  type: ClusterIP
