apiVersion: v2
name: postgresql
version: 1.0.0
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.29.0
  - name: dbclaim-operator
    repository: oci://ghcr.io/wyvernzora/charts
    version: 0.3.1
