argo-cd:
  secret:
    createSecret: false
  server:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: k2-auth-authelia@kubernetescrd
      hostname: deploy.wyvernzora.io
  repoServer:
    env:
      - name: ARGOCD_GIT_MODULES_ENABLED
        value: "false"
    extraContainers:
      - name: k2-plugin
        image: ghcr.io/wyvernzora/k2-argocd-plugin:latest
        command:
          - /var/run/argocd/argocd-cmp-server
        volumeMounts:
          - name: var-files
            mountPath: /var/run/argocd
          - name: plugins
            mountPath: /home/argocd/cmp-server/plugins
          - name: k2-working-dir
            mountPath: /tmp
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
    volumes:
      - name: k2-working-dir
        emptyDir: {}
  configs:
    params:
      # Let ingress handle TLS termination
      server.insecure: true
      # Disable builtin auth and let Authelia handle it
      server.disable.auth: true
    cm:
      statusbadge.enabled: true
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
        if obj.status.health ~= nil then
            hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                end
        end
        end
        return hs
