argo-cd:
  secret:
    createSecret: false
  server:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: k2-auth-authelia@kubernetescrd
      hostname: deploy.wyvernzora.io
  configs:
    params:
      # Let ingress handle TLS termination
      server.insecure: true
      # Disable builtin auth and let Authelia handle it
      server.disable.auth: true
    cm:
      statusbadge.enabled: true
      reposerver.enable.git.submodule: false
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
        if obj.status.health ~= nil then
            hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                end
        end
        end
        return hs
