apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: authelia
  namespace: k2-core
spec:
  destination:
    namespace: k2-auth
    server: https://kubernetes.default.svc
  project: default
  source:
    path: authelia
    repoURL: https://github.com/wyvernzora/k2
    targetRevision: deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
