#!/bin/bash

ROOT=$(dirname $0)
TYPE="$1"
HOST="$2"

help() {
    echo -e "Usage: configure-node <type> <host>\n"
    echo -e "Available node types:\n"
    echo -e "\tbootstrap\t\tFirst master node in the cluster"
    echo -e "\tmaster\t\tSubsequent master nodes"
    echo -e "\tworker\t\tWorker nodes"
}


CONFIG_FILE=""
case "$TYPE" in
    b|bootstrap)
        CONFIG_FILE="$ROOT/../kairos/cloud-config/bootstrap.yaml"
        ;;
    m|master)
        CONFIG_FILE="$ROOT/../kairos/cloud-config/master.yaml"
        ;;
    w|worker)
        CONFIG_FILE="$ROOT/../kairos/cloud-config/worker.yaml"
        ;;
    *)
        help
        echo -e "\nUnknown node type: $TYPE"
        exit 1
        ;;
esac

echo -e "Using config file $CONFIG_FILE"
op inject -i "$CONFIG_FILE" | sshpass -p "kairos" ssh "kairos@$HOST" "cat > cloud-config.yaml && sudo kairos-agent --debug manual-install --reboot cloud-config.yaml"
