#!/bin/bash

HOST="$1"

if [ -z "$HOST" ]; then
    echo "Usage: get-kubeconfig <HOST>"
    exit 1
fi

K8S_HOST="10.10.8.2"
echo "determining if kube-vip is online" >&2
ping -c 1 -W 1 "$K8S_HOST" &> /dev/null
if [ $? -ne 0 ]; then
    echo "kube-vip is not reachable, falling back to host IP" >&2
    K8S_HOST="$HOST"
fi

ssh "kairos@$HOST" "sudo cat /etc/rancher/k3s/k3s.yaml" | sed "s/127\.0\.0\.1/$K8S_HOST/"
