VERSION 0.8

image:
    FROM willhallonline/ansible:2.18-alpine-3.18
    WORKDIR /ansible

    COPY requirements.yml requirements.yml
    RUN ansible-galaxy install -r requirements.yml

    COPY . /ansible

    VOLUME [ "/ansible", "/root/.ssh" ]
    ENTRYPOINT [ "/ansible/entrypoint.sh" ]
