---
- name: set up fish shell for user
  become: yes
  become_user: '{{ item }}'
  block:
    - name: ensure config directory exists
      ansible.builtin.file:
        path: ~{{ item }}/.config/fish/functions
        owner: '{{ item }}'
        state: directory

    - name: install fisher
      ansible.builtin.get_url:
        url: https://git.io/fisher
        dest: ~{{ item }}/.config/fish/functions/fisher.fish

    - name: copy fisher plugins file
      copy:
        src: files/fish_plugins
        dest: ~{{ item }}/.config/fish/fish_plugins
      diff: yes
      register: __fisher_config

    - name: update fisher plugins
      ansible.builtin.shell:
        cmd: 'fisher update'
        executable: /bin/fish
      when: __fisher_config.changed
      register: __fisher_update

    - name: copy fisher config file
      ansible.builtin.copy:
        src: files/config.fish
        dest: ~{{ item }}/.config/fish/config.fish
        owner: '{{ item }}'
        mode: 0755

    - name: make fish default shell
      user:
        name: '{{ item }}'
        shell: /usr/bin/fish
