---
- name: proxmox.shell | install fish
  apt:
    name: fish
    state: latest
  register: __install_fish

- name: proxmox.shell | ensure config directory exists
  become_user: '{{ username }}'
  ansible.builtin.file:
    path: ~{{ username }}/.config/fish/functions
    owner: '{{ username }}'
    state: directory

- name: proxmox.shell | install fisher
  become_user: '{{ username }}'
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: ~{{ username }}/.config/fish/functions/fisher.fish
  # when: __install_fish.changed

- name: proxmox.shell | copy fisher plugins file
  become_user: '{{ username }}'
  ansible.builtin.copy:
    src: files/fish_plugins
    dest: ~{{ username }}/.config/fish/fish_plugins
    owner: '{{ username }}'
  register: __fisher_config

- name: proxmox.shell | update fisher plugins
  become_user: '{{ username }}'
  ansible.builtin.command:
    cmd: /usr/bin/fish -c 'fisher update'
  when: __fisher_config.changed

- name: proxmox.shell | copy fisher config file
  become_user: '{{ username }}'
  ansible.builtin.copy:
    src: files/config.fish
    dest: ~{{ username }}/.config/fish/config.fish
    owner: '{{ username }}'
    mode: 755

- name: proxmox.shell | make fish default shell
  become_user: '{{ username }}'
  user:
    name: '{{ username }}'
    shell: /usr/bin/fish
