gitops:
    repo: https://github.com/wyvernzora/k2
    revision: main

syncWaves:

  - apps:
    - name: crds
      path: crds
      namespace: default
      autoSync: false

  - apps:
    - name: kube-vip
      path: gitops/network/kube-vip
    - name: metallb
      path: gitops/network/metallb
      namespace: metallb-system
    - name: 1password
      path: gitops/core/1password

  - apps:
    - name: cert-manager
      path: gitops/network/cert-manager
    - name: longhorn
      path: gitops/storage/longhorn
      namespace: longhorn-system

  - apps:
    - name: traefik
      path: gitops/network/traefik
      ignoreDifferences:
        - kind: IngressRoute
          name: traefik-dashboard
    - name: dns
      path: gitops/network/dns

  - apps:
      name: glauth
      path: gitops/auth/glauth

  - apps:
    - name: argocd
      path: gitops/core/argocd
      namespace: argocd
