gitops:
    repo: https://github.com/wyvernzora/k2
    revision: main

syncWaves:
  - apps:
    - name: crds
      path: gitops/infra/crds
      namespace: default
      autoSync: false
    - name: kube-vip
      path: gitops/infra/kube-vip
    - name: metallb
      path: gitops/infra/metallb
      namespace: metallb-system
    - name: 1password
      path: gitops/infra/1password
  - apps:
    - name: cert-manager
      path: gitops/infra/cert-manager
  - apps:
    - name: traefik
      path: gitops/infra/traefik
      ignoreDifferences:
        - kind: IngressRoute
          name: traefik-dashboard
  - apps:
    - name: argocd
      path: gitops/infra/argocd
      namespace: argocd
