---
- name: Install nginx
  become_user: root
  package:
    name: nginx
    state: latest

- name: Remove default nginx config
  become_user: root
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx config for proxmox
  become_user: root
  copy:
    src: files/proxmox.conf
    dest: /etc/nginx/conf.d/proxmox.conf

- name: Copy SSL certificates
  become_user: root
  copy:
    src: files/{{ item }}
    dest: /etc/pve/local/{{ item }}
  with_items:
    - pve-ssl.pem
    - pve-ssl.key

- name: Restart and enable nginx service
  become_user: root
  systemd:
    name: nginx
    enabled: true
    state: restarted
