---
- name: add user to the proxmox pam
  ansible.builtin.shell:
    cmd: /usr/sbin/pveum user add "{{ user.username }}@pam"
  become: yes
  when: __user_create.append

- name: add user to the proxmox admins group
  ansible.builtin.shell:
    cmd: /usr/sbin/pveum acl modify / --roles Administrator --users {{ user.username }}@pam
  become: yes
  when: __user_create.append
