apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: v0.8.0
    helm.sh/chart: kube-vip-0.6.0
  name: kube-vip
  namespace: k2-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: kube-vip
  namespace: k2-network
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - services/status
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - list
      - get
      - watch
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: v0.8.0
    helm.sh/chart: kube-vip-0.6.0
  name: kube-vip
  namespace: k2-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: k2-network
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: k2-network
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-vip
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kube-vip
        app.kubernetes.io/name: kube-vip
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - args:
            - manager
          env:
            - name: vip_address
              value: 10.10.8.2
            - name: cp_enable
              value: "true"
            - name: lb_enable
              value: "true"
            - name: lb_port
              value: "6443"
            - name: svc_election
              value: "false"
            - name: svc_enable
              value: "false"
            - name: vip_arp
              value: "true"
            - name: vip_cidr
              value: "32"
            - name: vip_interface
              value: ""
            - name: vip_leaderelection
              value: "true"
          image: ghcr.io/kube-vip/kube-vip:v0.8.0
          imagePullPolicy: IfNotPresent
          name: kube-vip
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
