---
- name: Load K3s leader node info
  become: no
  delegate_to: localhost
  include_vars:
    file: .state/k3s-leader.yaml

- name: Fetch kube-vip releases
  become: no
  run_once: yes
  delegate_to: localhost
  uri:
    url: https://api.github.com/repos/kube-vip/kube-vip/releases
    return_content: yes
  register: __kube_vip_releases
  when: kube_vip_version is not defined

- name: Determine latest release
  become: no
  run_once: yes
  delegate_to: localhost
  set_fact:
    kube_vip_version: "{{ __kube_vip_releases.content | from_json | json_query('[].tag_name | [0]') }}"
  when: __kube_vip_releases.content is defined

- name: Copy RBAC manifest
  template:
    src: kube-vip.rbac.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.rbac.yaml
    owner: root
    group: root
    mode: 0644
  when: ansible_host == k3s_leader.host

- name: Copy VIP manifest
  template:
    src: kube-vip.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: 0644
  when: ansible_host == k3s_leader.host
