apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect-operator
  namespace: k2-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect-operator
  namespace: k2-core
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - onepassword-connect-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - onepassword.com
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect-operator
  namespace: k2-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepassword-connect-operator
subjects:
  - kind: ServiceAccount
    name: onepassword-connect-operator
    namespace: k2-core
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect
  namespace: k2-core
spec:
  ports:
    - name: connect-sync
      port: 8081
    - name: connect-api
      port: 8080
  selector:
    app: onepassword-connect
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect
  namespace: k2-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.7.3
    spec:
      containers:
        - env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_HTTP_PORT
              value: "8080"
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-api:1.7.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 0.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
        - env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-sync:1.7.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-sync
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - emptyDir: {}
          name: shared-data
        - name: credentials
          secret:
            secretName: op-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: onepassword-connect-operator
  namespace: k2-core
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        name: onepassword-connect
    spec:
      containers:
        - args:
            - --zap-log-level=info
          command:
            - /manager
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: onepassword-connect-operator
            - name: POLLING_INTERVAL
              value: "600"
            - name: AUTO_RESTART
              value: "false"
            - name: OP_CONNECT_HOST
              value: http://onepassword-connect:8080
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: onepassword-token
          image: 1password/onepassword-operator:1.9.1
          imagePullPolicy: IfNotPresent
          name: onepassword-connect
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            runAsGroup: 65532
            runAsUser: 65532
      serviceAccountName: onepassword-connect-operator
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-2.0.2
  name: 1password-health-check
  namespace: k2-core
spec:
  containers:
    - command:
        - curl
        - http://onepassword-connect:8080/health
      image: curlimages/curl
      name: curl
  restartPolicy: Never
