---
# Source: 1password/charts/connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: k2-core
  labels:
    app.kubernetes.io/component: connect
    helm.sh/chart: connect-1.15.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/version: "1.7.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api
---
# Source: 1password/charts/connect/templates/connect-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: k2-core
  labels:
    app.kubernetes.io/component: connect
    helm.sh/chart: connect-1.15.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/version: "1.7.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        version: "1.7.2"
        app.kubernetes.io/component: connect
    spec:
      volumes:
        - name: shared-data
          emptyDir:
            {}
        - name: credentials
          secret:
            secretName: op-credentials
      tolerations:
        []
      containers:
        - name: connect-api
          image: 1password/connect-api:1.7.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          resources:
            {}
          env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: op-credentials
                  key: 1password-credentials.json
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_HTTP_PORT
              value: "8080"
            - name: OP_LOG_LEVEL
              value: "info"            
          readinessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15
          
          livenessProbe:
            httpGet:
              path: /heartbeat
              scheme: HTTP
              port: 8080
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15
          
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
        - name: connect-sync
          image: 1password/connect-sync:1.7.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          resources:
            {}
          env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: op-credentials
                  key: 1password-credentials.json
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: "info"            
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15
          
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
---
# Source: 1password/charts/connect/templates/tests/health-check.yml
apiVersion: v1
kind: Pod
metadata:
  name: "1password-health-check"
  namespace: k2-core
  labels:
    helm.sh/chart: connect-1.15.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: 1password
    app.kubernetes.io/version: "1.7.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl
      command: ["curl", "http://onepassword-connect:8080/health"]
