argo-cd:
    secret:
        createSecret: false
    ingress:
        enabled: true
        hosts:
          - cd.wyvernzora.io
        
    configs:
        crds:
            # CRDs should be installed as part of k2-crds bundle on cluster bootstrap
            install: false
        params:
            # Let ingress handle TLS termination
            server.insecure: true
        repoServer:
            env:
                # Disable recursive checkout of submodules
              - name: ARGOCD_GIT_MODULES_ENABLED
                value: false
        cm:
            statusbadge.enabled: "true"
            resource.customizations.health.argoproj.io_Application: |
                hs = {}
                hs.status = "Progressing"
                hs.message = ""
                if obj.status ~= nil then
                if obj.status.health ~= nil then
                    hs.status = obj.status.health.status
                        if obj.status.health.message ~= nil then
                            hs.message = obj.status.health.message
                        end
                end
                end
                return hs
