name: Build and publish Ansible image

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    REGISTRY_IMAGE: ghcr.io/wyvernzora/k2-ansible

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: meta
              name: Docker meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY_IMAGE }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ env.REGISTRY_USER }}
                  password: ${{ env.REGISTRY_PASSWORD }}
            
            - id: build
              name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./ansible
                  platforms: linux/amd64,linux/arm64
                  labels: ${{ steps.meta.outputs.labels }}
                  push: true
                  tags: ${{ env.REGISTRY_IMAGE }}:latest
