name: Build and publish Ansible image
on:
  push:
      branches:
        - main
      paths:
        - 'ansible/**'
  pull_request:
      paths:
        - 'ansible/**'
  release:
      types:
        - published
jobs:
    build-ansible:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: earthly/actions-setup@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                version: "latest"

          - name: Login to ghcr.io
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        
          - name: Build and publish
            working-directory: ./kairos
            run: earthly --ci --push +ansible

          - name: Clean up old versions
            uses: actions/delete-package-versions@v4
            with:
                package-name: k2-ansible
                package-type: container
                min-versions-to-keep: 10
