name: Ansible
on:
  push:
    branches:
      - "dev"
      - "main"
    tags:
      - "v*"
    paths:
      - "ansible/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "ansible/**"
  release:
    types:
      - published
jobs:
  build-image:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' || github.event.pull_request.user.login == 'renovate[bot]'
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/wyvernzora/k2-ansible
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and publish
        run: |
          earthly --strict +ansible-multiarch
          for tag in ${{ steps.meta.outputs.tags }}; do
            docker tag ghcr.io/wyvernzora/k2-ansible:dev "$tag"
            docker push "$tag"
          done

      - name: Clean up old versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: k2-ansible
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: "true"
