name: 🏗️ Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - renovate/*
  schedule:
    - cron: "0 3 * * 0" # every Sunday 03:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref }}
  cancel-in-progress: true

jobs:
  # 1) Build Kubernetes deployment manifests
  manifests:
    name: 📜 Build k8s deployment manifests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v6

      - name: 🌍 Setup earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.14

      - name: ⚙️ Run manifest build & diff
        run: |
          earthly +lint
          earthly +k8s-manifests
          earthly +diff-manifests

      - name: 📦 Upload deploy-diff.md
        uses: actions/upload-artifact@v7
        with:
          name: deploy-diff
          path: deploy-diff.md
          if-no-files-found: error

      - name: 📦 Upload k8s manifests
        uses: actions/upload-artifact@v7
        with:
          name: k8s-manifests
          path: ./deploy
          if-no-files-found: error
          retention-days: 7

  # 2) Push manifests to deploy branch if push to main
  deploy:
    name: 🚀 Deploy k8s manifests
    needs: manifests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !failure() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download k8s manifests
        uses: actions/download-artifact@v8
        with:
          name: k8s-manifests
          path: artifacts

      - name: 🔐 Create deploy app token
        id: deploy-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.K2_DEPLOY_APP_CLIENT_ID }}
          private-key: ${{ secrets.K2_DEPLOY_APP_PRIVATE_KEY }}
          permission-contents: write

      - name: 🚢 Push to deploy branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: artifacts
          GITHUB_TOKEN: ${{ steps.deploy-token.outputs.token }}
          SKIP_EMPTY_COMMITS: true
