name: Containers
on:
  push:
    branches:
      - "dev"
      - "main"
    tags:
      - "v*"
  release:
    types:
      - published
jobs:
  build-image:
    name: Build container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/wyvernzora/k2-${{ matrix.image }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "containers/${{ matrix.image }}/Dockerfile"
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
      - name: Clean up old versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: k2-${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 3
