name: CRDs
on:
    push:
        branches:
          - main
        paths:
          - 'crds/**'
    pull_request:
        paths:
          - 'crds/**'
    release:
        types:
          - published
jobs:
    build-crds-image:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: earthly/actions-setup@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                version: "latest"

          - name: Login to ghcr.io
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and publish
            run: earthly --ci --push +crds

          - name: Clean up old versions
            uses: actions/delete-package-versions@v4
            with:
                package-name: k2-crds
                package-type: container
                min-versions-to-keep: 10
