name: Kairos
on:
    push:
        branches:
          - '**'
        tags:
          - 'v*'
        paths:
          - 'kairos/cluster-init/**'
          - '.github/workflows/**'
    pull_request:
        paths:
          - 'kairos/cluster-init/**'
    release:
        types:
          - published
jobs:
    build-image:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: earthly/actions-setup@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                version: "latest"

          - name: Login to ghcr.io
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        
          - name: Determine the image tag
            shell: bash
            run: |
                if [[ $GITHUB_REF == refs/tags/* ]]; then
                    TAG="${GITHUB_REF#refs/tags/}"
                else
                    BRANCH_TAG=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9._-]/-/g')
                    TAG="${BRANCH_TAG}"
                fi
                echo "TAG=${TAG}" >> $GITHUB_ENV

          - name: Build and publish
            run: earthly --ci --push +cluster-init --TAG=${{ env.TAG }}

          - name: Clean up old versions
            uses: actions/delete-package-versions@v4
            with:
                package-name: k2-cluster-init
                package-type: container
                min-versions-to-keep: 3
                delete-only-untagged-versions: 'true'
