name: Kairos
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-bundles:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        strategy:
            matrix:
                bundles:
                    - 1password-connect
                    - argocd
                    - kube-vip
                    - traefik
        env:
            REGISTRY: ghcr.io
            REGISTRY_USER: ${{ secrets.REGISTRY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: docker-practice/actions-setup-docker@master
            - uses: earthly/actions-setup@v1
              with:
                  version: "latest"
            - uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and publish
              working-directory: ./kairos
              run: earthly --ci --push +build --BUNDLE=${{ matrix.bundles }}
