apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.crds.yaml
    - https://github.com/traefik/traefik-helm-chart/traefik/crds/?ref=v26.0.0
